# Change these first
owner: jamiew0w
repo: status.welp.me
  
# Add your sites here
sites:
  - name: welp.me
    url: https://welp.me
  - name: ts.welp.me
    check: "tcp-ping"
    url: ts.welp.me
    port: 10011
  - name: cs.welp.me
    check: "tcp-ping"
    url: cs.welp.me
    port: 27015
  - name: mc.welp.me
    check: "tcp-ping"
    url: mc.welp.me
    port: 25566
  - name: valheim.welp.me
    check: "tcp-ping"
    url: valheim.welp.me
    port: 2457

assignees:
  - jamiew0w

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.welp.me
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.welp.me
  theme: dark

i18n:
  footer: <a href="https://welp.me" target="_blank">welp.me</a>

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
